### ISSUE TITLE
attempt vrecord linux brew ubuntu 18.04 INSTALL problem

### ISSUE THREAD

**Issue by jshupeGitHub** [amiaopensource/homebrew-amiaos#236] opened 2020-04-14 15:26 UTC
I have resolved previous problems with sdl and cowsay

but now am stuck

i think I have my PATH ok
i did the suggested echos

brew doctor

Warning: Homebrew’s bin was not found in your PATH.
Consider setting the PATH for example like so:
echo ‘export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"’ >> ~/.bash_profile

Warning: Homebrew’s sbin was not found in your PATH but you have installed
formulae that put executables in /home/linuxbrew/.linuxbrew/sbin.
Consider setting the PATH for example like so:
echo ‘export PATH="/home/linuxbrew/.linuxbrew/sbin:$PATH"’ >> ~/.bash_profile

i seem to be stuck on a last step

brew install vrecord
==> Installing vrecord from amiaopensource/amiaos
Error: undefined method installed?' for OS::Mac::Xcode:Module Please report this issue: https://docs.brew.sh/Troubleshooting /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirements/xcode_requirement.rb:18:in xcode_installed_version’
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirements/xcode_requirement.rb:10:in block in <class:XcodeRequirement>' /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:60:in instance_eval’
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:60:in block in satisfied?' /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:191:in yielder’
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:60:in satisfied?' /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:456:in block in expand_requirements’
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:222:in block in prune?' /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:220:in catch’
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:220:in prune?' /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:210:in block (2 levels) in expand’
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/set.rb:338:in each_key' /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/set.rb:338:in each’
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/delegate.rb:349:in block in delegating_block' /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:209:in block in expand’
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:208:in each' /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:208:in expand’
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1557:in recursive_requirements' /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:450:in expand_requirements’
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:388:in compute_dependencies' /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:148:in verify_deps_exist’
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:141:in prelude' /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:328:in install_formula’
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:261:in block in install' /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:259:in each’
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:259:in install' /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:110:in ’

------{ it is possible that the clue to solution is in the above ...and I fail to understand it--------

presently I am attempting to whittle my way through
with a

brew install --ignore-dependencies vrecord

and when that fails with a child process - then I respond to that
here you can see  a few attempts on that
giflib ,  leptonica ,  tesseract  and on and on 

</snip
Error: An exception occurred within a child process:
RuntimeError: /home/linuxbrew/.linuxbrew/opt/giflib not present or broken
Please reinstall giflib. Sorry :(

brew install giflib

scenesavers@ss-43:~$ brew install giflib
==> Downloading https://linuxbrew.bintray.com/bottles/giflib-5.2.1.x86_64_linux.
######################################################################## 100.0%
==> Pouring giflib-5.2.1.x86_64_linux.bottle.tar.gz
🍺 /home/linuxbrew/.linuxbrew/Cellar/giflib/5.2.1: 34 files, 553.4KB

brew install --ignore-dependencies vrecord

Error: An exception occurred within a child process:
RuntimeError: /home/linuxbrew/.linuxbrew/opt/leptonica not present or broken
Please reinstall leptonica. Sorry :(

brew install leptonica

scenesavers@ss-43:~$ brew install leptonica
==> Downloading https://linuxbrew.bintray.com/bottles/leptonica-1.79.0.x86_64_li
==> Downloading from https://akamai.bintray.com/ad/ad22d307cd6b6c1a08d2931e878dd
######################################################################## 100.0%
==> Pouring leptonica-1.79.0.x86_64_linux.bottle.tar.gz
🍺 /home/linuxbrew/.linuxbrew/Cellar/leptonica/1.79.0: 53 files, 8.5MB

brew install --ignore-dependencies vrecord

Error: An exception occurred within a child process:
RuntimeError: /home/linuxbrew/.linuxbrew/opt/tesseract not present or broken
Please reinstall tesseract. Sorry :(
</snip

maybe there is a "better" flag  for linux  ubuntu 18.4
besides
" --ignore-dependencies "
but would autoMagically get the dependencies

or how do I "adjust" my $PATH   to point to things ...that maybe I do have in sbin and on like that
OR
maybe this is the best way....
I would also benefit from a word of
YES- that will eventually work and you will vrecord on linux 18.04 and can happily capture directly into ffv1 v3 into a mkv
or or
NO- that will never work

any assistance would be welcomed

thanks in advance

best wishes

jim shupert

**Comment by retokromer** [comment] 2020-04-14 16:20
Duplicate of https://github.com/amiaopensource/vrecord/issues/528.

**Comment by privatezero** [comment] 2020-04-14 16:52
@retokromer, have you run into this (what appears to be) upstream issue, where despite using the `--ignore-dependencies` flag linuxbrew will seek out every dependency one by one?

Could it be time to modify the install formula to do a system check and to cut down on as many dependencies as possible in Linux while referring people to the install docs?

**Comment by retokromer** [comment] 2020-06-17 05:14
@privatezero I suggest to close this one, because the current version `2020-02-10` is now 158 commits (with 1,374 additions and 638 deletions) behind the HEAD. Very much has been modified!

**Comment by retokromer** [comment] 2020-07-01 19:31
Closing, because a new release was made.

**Closed by retokromer** 2020-07-01 19:31 UTC

**Comment by privatezero** [comment] 2020-07-01 19:48
I imagine this should be resolved in latest release as it eliminates the need for `--ignore-dependencies` thus hopefully avoiding the upstream issue
